name: test-and-connect-publish
'on':
  push:
    branches:
      - feature_chaitra
  pull_request:
    branches:
      - feature_chaitra
jobs:
  test-and-connect-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.3
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
      - name: Test Shiny App
        shell: 'Rscript {0}'
        run: |
          shinytest2::test_app()
      - name: Create manifest.json
        shell: 'Rscript {0}'
        run: |
          rsconnect::writeManifest()
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: '${{ https://dev.positconnect.analytics.kellogg.com }}'
          api-key: '${{ h4tiXtqqyjeXeAKLv1cPMSQoMK1AJoLg }}'
          access-type: logged_in
          dir: |
            .:/shiny-app-demo-cicd-github-actions
