  name: test-and-connect-publish-shiny
  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  
  jobs:
    test-and-connect-publish-shiny:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2

        - uses: r-lib/actions/setup-pandoc@v2

        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: 4.2.3
            use-public-rspm: true
            
        - name: Install shinytest2
          run: Rscript -e "install.packages(c('shinytest2','rsconnect'))"

        - name: Create shinytest2 setup file
          run: R -e 'shinytest2::use_shinytest2(".", setup = TRUE)'
               
        - name: Create manifest.json
          shell: Rscript {0}
          run: |
            rsconnect::writeManifest()
            
        - name: Publish Connect content
          uses: rstudio/actions/connect-publish@main
          with:
            url: "https://uat.rstudioconnect.analytics.kellogg.com"
            api-key: "dZ23PaXzh0rxQgFS4R7GuF7LagtdAi54"
            access-type: logged_in
            dir: |
              .:/appnewshiny
