  name: Install R Packages
  on:
    push:
      branches: [feature_sav]
  
  jobs:
    deploy:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
            
        - name: Install dependencies
          run: |
            R -e 'install.packages("rsconnect")'
        
        - name: Deploy to RStudio connect
          run: |
            R -e 'rsconnect::setAccountInfo(name="savanchitragar",token = Sys.getenv("ZDzo2nOH0lk7onDX0hWqzJwSD0q6SqBg"),apiurl="https://dev.positconnect.analytics.kellogg.com")'
            R -e 'rsconnect::deployApp(appDir= "shinytestapp")'
         
